/**
 * RT-217 — the `contracts/backend-core/PIN` file format, shared by the re-pin
 * script (`scripts/contracts-repin.ts`) and the contract-conformance suite
 * (`tests/contract/backend-core/`). Pure: no I/O.
 *
 * The PIN records which Backend-Core commit the vendored OpenAPI contracts came
 * from and the git blob SHA of every vendored file, so the suite can prove the
 * snapshot is exactly what Backend-Core published at that commit (no hand edits).
 */
import { createHash } from 'node:crypto';

/** Where the vendored contracts live in Backend-Core. */
export const BACKEND_CORE_REPO = 'Kemetra/Backend-Core';
export const BACKEND_CORE_OPENAPI_ROOT = 'packages/contracts/openapi';

export interface PinnedFile {
  /** Path relative to `packages/contracts/openapi/` (and to `contracts/backend-core/openapi/`). */
  readonly path: string;
  /** Git blob SHA-1 of the file's bytes at `commit`. */
  readonly blobSha: string;
}

export interface ContractsPin {
  readonly repo: string;
  readonly commit: string;
  readonly source: string;
  readonly files: readonly PinnedFile[];
}

const HEADER = [
  '# Backend-Core OpenAPI contracts vendored for the POS contract-conformance suite',
  '# (tests/contract/backend-core, RT-217). Generated by `npm run contracts:repin`.',
  '# Do not hand-edit: the suite checks every file below against its git blob SHA.',
];

const SHA1 = /^[0-9a-f]{40}$/;

/** The git blob SHA-1 of `bytes` (what `git hash-object` prints). */
export function gitBlobSha(bytes: Uint8Array): string {
  return createHash('sha1')
    .update(`blob ${String(bytes.byteLength)}\0`)
    .update(bytes)
    .digest('hex');
}

/** Reject anything that could escape the vendored directory. */
export function assertSafeRelativePath(p: string): void {
  if (
    p.length === 0 ||
    p.startsWith('/') ||
    p.includes('\\') ||
    p.split('/').some((seg) => seg === '' || seg === '.' || seg === '..') ||
    !/\.(ya?ml|json)$/.test(p)
  ) {
    throw new Error(`contracts PIN: unsafe or non-OpenAPI path "${p}"`);
  }
}

export function formatPin(pin: ContractsPin): string {
  const files = [...pin.files].sort((a, b) => a.path.localeCompare(b.path));
  return [
    ...HEADER,
    `repo: ${pin.repo}`,
    `commit: ${pin.commit}`,
    `source: ${pin.source}`,
    ...files.map((f) => `file: ${f.path} ${f.blobSha}`),
    '',
  ].join('\n');
}

export function parsePin(text: string): ContractsPin {
  let repo: string | null = null;
  let commit: string | null = null;
  let source: string | null = null;
  const files: PinnedFile[] = [];
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (line === '' || line.startsWith('#')) continue;
    const m = /^([a-z]+):\s+(.+)$/.exec(line);
    if (m === null) throw new Error(`contracts PIN: unparseable line "${line}"`);
    const key = m[1] as string;
    const value = (m[2] as string).trim();
    if (key === 'repo') repo = value;
    else if (key === 'commit') commit = value;
    else if (key === 'source') source = value;
    else if (key === 'file') {
      const parts = value.split(/\s+/);
      const [path, blobSha] = parts;
      if (
        parts.length !== 2 ||
        path === undefined ||
        blobSha === undefined ||
        !SHA1.test(blobSha)
      ) {
        throw new Error(`contracts PIN: malformed file line "${line}"`);
      }
      assertSafeRelativePath(path);
      files.push({ path, blobSha });
    } else {
      throw new Error(`contracts PIN: unknown key "${key}"`);
    }
  }
  if (repo === null || commit === null || source === null) {
    throw new Error('contracts PIN: repo, commit and source are all required');
  }
  if (!SHA1.test(commit)) throw new Error(`contracts PIN: commit "${commit}" is not a full SHA`);
  if (files.length === 0) throw new Error('contracts PIN: no files pinned');
  if (new Set(files.map((f) => f.path)).size !== files.length) {
    throw new Error('contracts PIN: duplicate file entry');
  }
  return { repo, commit, source, files };
}
